all: makeC makeJava makePython
makeC:
	gcc -std=c99 c/MergeSort.c -o c/MergeSort.out -g
makeJava:
makePython:
clean:
	rm -rf clr_16_MergeSort/c/*.out
	rm -rf clr_16_MergeSort/java/*.class
	rm -rf clr_16_MergeSort/py/*.pyc

