all: makeC makeJava makePython
makeC:
	gcc -std=c99 c/MaximumSubArray.c -o c/MaximumSubArray.out -g
makeJava:
makePython:
clean:
	rm -rf clr_68_MaximumSubArray/c/*.out
	rm -rf clr_68_MaximumSubArray/java/*.class
	rm -rf clr_68_MaximumSubArray/py/*.pyc

