all: makeC makeJava makePython
makeC:
	gcc -std=c99 c/InsertionSort.c -o c/InsertionSort.out
makeJava:
makePython:
clean:
	rm -rf clr_16_InsertionSort/c/*.out
	rm -rf clr_16_InsertionSort/java/*.class
	rm -rf clr_16_InsertionSort/py/*.pyc

